# Copyright 2015 basebuilder authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# this file describes how to build a tsuru drupal platform
# to run it:
# 1- run: $ tsuru-admin platform-add drupal -d https://raw.github.com/badri/basebuilder/master/drupal/Dockerfile

FROM    minnal/drupal-alpine
