# Copyright 2015 basebuilder authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# this file describes how to build a tsuru drupal 7 image
# to run it:
# 1- run: $ tsuru-admin platform-add drupal -d https://raw.github.com/badri/basebuilder/master/php/Dockerfile

FROM	tsuru/php
